
FT_DPCM_PTR=$c000
	.export _danger_streets_music_data
;this file for FamiTone2 library generated by text2data tool
_danger_streets_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env6,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00
	.byte $70 ;instrument $04
	.word @env5,@env7,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c8,$c9,$ca,$ca,$cb,$02,$c9,$c9,$c8,$02,$c7,$0f,$c6,$0d,$c5,$09
	.byte $c4,$05,$c4,$00,$12
@env2:
	.byte $ce,$02,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$c5,$c5,$c4
	.byte $00,$0f
@env3:
	.byte $cc,$c9,$c8,$c5,$c4,$c2,$c3,$02,$c2,$03,$c2,$00,$0a
@env4:
	.byte $cc,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env5:
	.byte $ce,$02,$cd,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c9,$02,$c8,$c8,$c8,$00
	.byte $0e
@env6:
	.byte $c0,$c1,$c0,$00,$02
@env7:
	.byte $c0,$c0,$c3,$c3,$c7,$c7,$c0,$c0,$00,$00


@song0ch0:
	.byte $fb,$01
@song0ch0loop:
@ref0:
	.byte $80,$3a,$c5,$3e,$c5
@ref1:
	.byte $40,$c5,$48,$c5
@ref2:
	.byte $4a,$c5,$3e,$c5
@ref3:
	.byte $40,$f9,$93
@ref4:
	.byte $3a,$c5,$3e,$c5
@ref5:
	.byte $40,$c5,$48,$c5
@ref6:
	.byte $4a,$c5,$3e,$c5
@ref7:
	.byte $40,$f9,$93
@ref8:
	.byte $4a,$95,$48,$95,$44,$95,$52,$95,$4e,$95,$4a,$95
@ref9:
	.byte $58,$95,$56,$95,$52,$95,$50,$c5
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	.byte $82,$0a,$95,$22,$95,$22,$95,$0a,$95,$22,$95,$22,$95
@ref11:
	.byte $0a,$95,$22,$95,$22,$95,$0a,$95,$22,$95,$22,$95
	.byte $ff,$0c
	.word @ref11
@ref13:
	.byte $0a,$95,$22,$95,$22,$95,$10,$95,$0e,$95,$0c,$95
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref11
@ref17:
	.byte $0a,$95,$22,$95,$22,$95,$28,$95,$26,$95,$24,$95
@ref18:
	.byte $88,$24,$f9,$93
@ref19:
	.byte $f9,$95
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	.byte $84,$0a,$95,$22,$95,$22,$95,$0a,$95,$22,$95,$22,$95
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref13
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref11
	.byte $ff,$0c
	.word @ref17
@ref28:
	.byte $88,$24,$f9,$93
@ref29:
	.byte $f9,$95
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref30:
	.byte $86,$20,$95,$18,$95,$18,$95,$20,$95,$18,$89,$1c,$89,$18,$95
@ref31:
	.byte $20,$95,$18,$95,$18,$95,$20,$95,$18,$95,$18,$95
@ref32:
	.byte $20,$95,$18,$95,$18,$95,$20,$95,$18,$89,$1c,$89,$18,$95
@ref33:
	.byte $20,$95,$18,$95,$18,$95,$06,$95,$04,$95,$02,$95
	.byte $ff,$0e
	.word @ref32
	.byte $ff,$0c
	.word @ref31
	.byte $ff,$0e
	.word @ref32
	.byte $ff,$0c
	.word @ref33
	.byte $ff,$0e
	.word @ref32
	.byte $ff,$0c
	.word @ref31
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref40:
	.byte $f9,$95
@ref41:
	.byte $f9,$95
@ref42:
	.byte $f9,$95
@ref43:
	.byte $f9,$95
@ref44:
	.byte $f9,$95
@ref45:
	.byte $f9,$95
@ref46:
	.byte $f9,$95
@ref47:
	.byte $f9,$95
@ref48:
	.byte $f9,$95
@ref49:
	.byte $f9,$95
	.byte $fd
	.word @song0ch4loop